KEYWORDS = {
    'wall',
    'antitrust',
    'investigation',
    'stock',
    'stocks',
    'investment',
    'invest',
    'investors',
    'return',
    'roi',
    'rate of return',
    'returned',
    'how to invest in stocks',
    'split stock',
    'get stock market data',
    'stock market stages',
    'bonds',
    'dividends',
    'market data',
    'annual returns',
    'profit',
    'quarter',
    'swing trading',
    'investment opportunity',
    'learn to invest money',
    'learning to invest',
    'candlestick',
    'stock market data information',
    'investment information',
    'business and finance',
    'how to invest your money',
    'historical market data',
    'trend trading',
    'dynamic stock market content',
    'rich',
    'financial news',
    'trading results',
    'best place to invest money',
    'listed companies',
    'direct access day trading',
    'stock market trend analysis',
    'aaii',
    'how to invest in stock',
    'daytrader',
    'stock market historical data',
    'value screen',
    'type of investor',
    'valuation range',
    'portfolio theory',
    'money to invest',
    'historical stock quotes',
    'good stock to invest',
    'investing forum',
    'longterm investments',
    'how to invest money',
    'how to invest in oil',
    'history market stock',
    'timing stock market investment',
    'active traders',
    'business information',
    'bear stock market',
    'how to invest online',
    'bear market',
    'shorting stocks',
    'stock market data feed',
    'personal finance',
    'market news',
    'how to pick stocks',
    'stock information',
    'doji',
    'direct investment',
    'corporation',
    'investing for beginners',
    'income investing',
    '52 week low',
    'day trading stock market',
    'stock market education',
    'insider trading tip',
    'american association of individual investors',
    'stock dividends',
    'how to invest',
    'analyze stocks',
    'history facts stock market',
    'trading analysis',
    'stock market charts',
    'how to invest in shares',
    'hammer pattern',
    'suze orman',
    'historic market data',
    'bluechip',
    'candlestick patterns',
    'investing stock market',
    'world stock market',
    'jim cramer',
    'bottom',
    'business and financial news',
    'cboe',
    'aaii sentiment survey',
    'stock charts',
    'stock price history',
    'breakout',
    'stock market performance',
    'tips',
    'publicly traded stocks',
    'stock market prices',
    'market stock trading',
    'company profile',
    'index investing',
    'history stock market',
    'technical analysis',
    'public company',
    'finance news',
    'bollinger bands',
    'stock market price',
    'stock market trading data provided',
    'wall street',
    'charts',
    'buy sell recommendation',
    'day trading market data',
    'stock market results',
    'derivative',
    'board of directors',
    'free real time data',
    'top gainers',
    'fundamental data',
    'invest in stocks',
    'stock market',
    'trading systems',
    'short selling stocks',
    'brokerage',
    'suzeorman',
    'investing tip stock market',
    'your money',
    'business innovation',
    'piercing candlestick pattern',
    'exhaustion gaps',
    'stock quote history',
    'harami',
    'bull or bear',
    'continuation gaps',
    'invest in the stock market',
    'stock terms',
    'trading seminar',
    'best stocks to buy',
    'money trading stocks',
    'chicago board options exchange',
    'stock trading information',
    'stock market quote',
    'invest in stock online',
    '52 week high',
    'stocks technical analysis',
    'stock market history',
    'brokers',
    'company research information',
    'financial information',
    'trader',
    'investment income',
    'madoff',
    'historical stock market data',
    'traded',
    'stock market commentary',
    'breakouts',
    'value of old certificates',
    'historical data',
    'price volatility',
    'investing stock market advice',
    'stock quotes',
    'absolute returns',
    'historical stock prices',
    'investor type',
    'best way to invest',
    'stock market technical analysis',
    'ways to invest money',
    'investment tips',
    'financial reports',
    'how to buy stocks',
    'history of stock market',
    'commodities',
    'stock quote',
    'how to make money',
    'bond',
    'stock market information',
    'how to sell stocks',
    'stock market info',
    'stock performance',
    'market research',
    'investing gurus',
    'stock trading pick',
    'quote server',
    'tarp',
    'stochastics',
    'derivatives',
    'how to invest wisely',
    'capital appreciation',
    'market information',
    'why do people invest',
    'investment timing',
    'day trading stock picks',
    'day traders',
    'how to trade stocks',
    'best place to invest',
    'price history',
    'assets',
    'analyst recommendations',
    'stock sectors',
    'historical stock data',
    'how to day trade stocks',
    'market statistics',
    'better investing',
    'wealth',
    'why invest in stocks',
    'fundamental financial data',
    'investing in stocks',
    'broker dealer',
    'stock investment',
    'stock price quote',
    'streaming charts',
    'reversal',
    'day trading information',
    'day trading',
    'money magazine',
    'business news',
    'mutual funds invest',
    'learn how to invest',
    'how to read stocks',
    'company share price',
    'investing like warren buffett',
    'declines',
    'stock market trading data',
    'stock analysis',
    'warren buffett',
    'candlestick charts',
    'money 101',
    'etf',
    'stock splits',
    'after hours markets',
    'capital markets',
    'downgrades',
    'stock market investing for dummies',
    'company profiles',
    'pre-market analysis',
    'dow jones',
    'bull market',
    'investment faqs',
    'junk bonds',
    'dow jones industrial average',
    'purchase stocks',
    'bearish',
    'amex',
    'djia',
    'help understanding stocks',
    'bernard madoff',
    'tracking stocks',
    'valuations',
    'online stock trading information',
    'chart',
    'public companies',
    'bull markets',
    'stockmarket',
    'historical stock quote',
    'stock market research',
    'stock investment research',
    'bulls or bears',
    'stock prices',
    'investment in stock',
    'day trading stocks',
    'active trader',
    'data information market stock summary',
    'closing prices',
    'historical quotes',
    'investment services',
    'bear markets',
    'buying stocks online',
    'stock market analysis',
    'stocks analysis',
    'markets',
    'company research',
    'broker',
    'stock market reports',
    'financial investments',
    'invest in stock market',
    'analyst',
    'market failure',
    'annual reports',
    'buying stocks',
    'historical intraday data',
    'free real time quotes',
    'investor awareness',
    'public company research',
    'invest in stock',
    'blue chip',
    'world business',
    '52 week lows',
    'aaii local chapter',
    'selecting stocks',
    'candlestick chart',
    'quote summary',
    'trading',
    'brokerage firm',
    'market summary',
    'market data history',
    'commission',
    'income investment',
    'stock trading seminar',
    'online swing trading',
    'technical analysis of stocks',
    'bear market definition',
    'stock trader',
    'stock trades',
    'top losers',
    'exchange traded funds',
    'market maker',
    'stock trade',
    'day trader',
    'how to trade stocks online',
    'expert speaks',
    'invest stock market',
    'stock market tips',
    'breakaway gaps',
    'engulfing',
    'buffettology',
    'investment concepts',
    'market data and information',
    'drip investing',
    'stock research',
    'ebitda',
    'learn day trading',
    'stocks and investing',
    'aaii.com',
    'bernie madoff',
    'save your money',
    'trading periods',
    'insider trading report',
    'best way to invest money',
    'stock market data',
    'save money',
    'investor sentiment',
    'paper trading',
    'stocks to invest',
    'learn to invest',
    'aaii journal',
    'fundamental analysis',
    'company earnings',
    'bullish',
    'profitability',
    'online brokers',
    'real time quotes',
    'markets and investments',
    'dow jones index',
    'benefits of trading',
    'investor advisory service',
    'prices of stocks',
    'macd',
    'losers',
    'best online trading',
    'trading markets',
    'list of stocks',
    'market reports',
}
